/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Empleado;

import Controlador.ControladorEmpleado;
import Controlador.ControladorPersona;
import Modelo.Personas.Persona.Empleado;
import Modelo.Personas.Persona.Persona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class ListarEmpleado extends javax.swing.JInternalFrame {
    private IngresaCedula ingresarCedula;
    private IngresaNombre ingresarNombre;
    private javax.swing.JDesktopPane desktopPane;
    private ControladorEmpleado controladorEmpleado;
    private ControladorPersona controladorPersona;
    /**
     * Creates new form ListarEmpleado
     */
    public ListarEmpleado(javax.swing.JDesktopPane p) {
        initComponents();
        buttonGroupSeleccion.add(jboxNombre);
        buttonGroupSeleccion.add(jboxTodo);
        buttonGroupSeleccion.add(Cedula);
        desktopPane = p;
        controladorPersona=new ControladorPersona();
        controladorEmpleado=new ControladorEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSeleccion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jBntSeleccionar = new javax.swing.JButton();
        jboxNombre = new javax.swing.JRadioButton();
        Cedula = new javax.swing.JRadioButton();
        jboxTodo = new javax.swing.JRadioButton();
        jBntCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Direccion", "Telefono", "Correo", "Permisos", "Visualizar"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        jBntSeleccionar.setText("Seleccionar");
        jBntSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntSeleccionarActionPerformed(evt);
            }
        });

        jboxNombre.setText("Nombre");
        jboxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxNombreActionPerformed(evt);
            }
        });

        Cedula.setText("Cedula");

        jboxTodo.setText("Listar todo");

        jBntCancelar.setText("Cancelar");
        jBntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Listar por :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jboxNombre)
                        .addGap(129, 129, 129)
                        .addComponent(Cedula)
                        .addGap(121, 121, 121)
                        .addComponent(jboxTodo)
                        .addGap(66, 66, 66)
                        .addComponent(jBntSeleccionar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBntCancelar)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jboxNombre)
                            .addComponent(Cedula)
                            .addComponent(jboxTodo)
                            .addComponent(jBntSeleccionar))
                        .addGap(55, 55, 55)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBntCancelar)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jboxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jboxNombreActionPerformed

    private void jBntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBntCancelarActionPerformed

    private void jBntSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntSeleccionarActionPerformed
        // TODO add your handling code here:
        if(Cedula.isSelected()||jboxNombre.isSelected()||jboxTodo.isSelected()){
            if (Cedula.isSelected()) {
                this.limpiarTabla();
                desplegarCedula();

                //wSystem.out.println(ingresarCedula.getVentanaCedula().getCedula());
            }else if(jboxNombre.isSelected()){
                this.limpiarTabla();
                desplegarNombre();

            }else if(jboxTodo.isSelected()){
                try {
                    this.limpiarTabla();
                    
                    this.desplegarTodo();
                } catch (SQLException ex) {
                    Logger.getLogger(ListarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }
                

            }
        }else{
            JOptionPane.showInternalMessageDialog(rootPane, "Escoja una opcion.");
        }
    }//GEN-LAST:event_jBntSeleccionarActionPerformed
    
    public void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTableEmpleados.getModel();
        model.setRowCount(0);
    }
    private void desplegarCedula(){
        
        if(ingresarCedula == null){
            ingresarCedula = new IngresaCedula(jTableEmpleados);
            desktopPane.add(ingresarCedula);
        }
        ingresarCedula.setVentanaCedula();
        ingresarCedula.setVisible(true); 
    }
    private void desplegarNombre(){
        
        if(ingresarNombre == null){
            ingresarNombre = new IngresaNombre(jTableEmpleados);
            desktopPane.add(ingresarNombre);
        }
        
        ingresarNombre.setVisible(true); 
    }
   private void desplegarTodo() throws SQLException{
       List<Persona> listaP = controladorPersona.listarPersonasClientes();
       if (listaP!=null) {
           List<Empleado> listaE = controladorEmpleado.ListarEmpleados(listaP);
           //List<Empleado> listaC = controladorCliente.buscarPorNombreCliente(listaP);
           if (listaE!=null) {
               this.llenarTabla(listaE);
           }else{
                JOptionPane.showInternalMessageDialog(rootPane, "No existe ningun cliente en la base de datos.");
           }
       }else{
           JOptionPane.showInternalMessageDialog(rootPane, "No existe ninguna persona en la base de datos.");
       }
   }
   public void llenarTabla(List<Empleado> clientes){
        String[] columnNames = {"Cedula", "Nombre", "Apellido", "Direccion", "Telefono", "Correo"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        jTableEmpleados.setModel(tableModel);
        for (Empleado emp : clientes) {
            if (emp.getVisualizacion()=='a') {
                Object[] rowData = {
                    emp.getCedula(),
                    emp.getNombre(),
                    emp.getApellido(),
                    emp.getDireccion(),
                    emp.getTelefono(),
                    emp.getCorreo()
                };
                tableModel.addRow(rowData);
            }
            
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cedula;
    private javax.swing.ButtonGroup buttonGroupSeleccion;
    private javax.swing.JButton jBntCancelar;
    private javax.swing.JButton jBntSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JRadioButton jboxNombre;
    private javax.swing.JRadioButton jboxTodo;
    // End of variables declaration//GEN-END:variables
}
